/*Eliminar Constraints*/
ALTER TABLE Employees DROP CONSTRAINT IF EXISTS FK_EmployeeRole;
ALTER TABLE Movimientos DROP CONSTRAINT IF EXISTS FK_MovEmployee;
ALTER TABLE Movimientos DROP CONSTRAINT IF EXISTS FK_MovRole;
ALTER TABLE Movimientos DROP CONSTRAINT IF EXISTS FK_MovMonth;

DROP TABLE IF EXISTS Roles;
DROP TABLE IF EXISTS Months;
DROP TABLE IF EXISTS Employees;
DROP TABLE IF EXISTS Movimientos;

DROP PROCEDURE SaveEmployee;
DROP PROCEDURE SaveMovimiento;
DROP PROCEDURE ConsultaSueldos;
DROP PROCEDURE BuscarId;
DROP PROCEDURE BuscarMov;